name: my_final_app # <--- 이 부분이 my_final_app으로 되어 있는지 확인
description: "A dumbbell exercise posture assistance system."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  google_mlkit_pose_detection: ^0.14.0
  google_mlkit_commons: ^0.11.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  collection: ^1.18.0
  vector_math: ^2.1.4
  flutter_blue_plus: ^1.31.5
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pose_landmarker_full.task
